name: Deploy static content to Render

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]


jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: Render Deploy Action
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.API_KEY }}
          api-key: ${{ secrets.SERVICE_ID }}
  
